version: '3'
services:
  backend:
    container_name: cnand-md-backend
    build:
      context: ./backend
    image: kinshuk4/cnand-md-backend
    ports:
      - '8081:8080'

  frontend:
    container_name: cnand-md-frontend
    build:
      context: ./frontend
    image: kinshuk4/cnand-md-frontend
    ports:
      - '8080:8080'
    depends_on:
      - backend

  trial:
    build:
      context: ./trial
    image: kinshuk4/cnand-md-trial
    ports:
      - '8083:8080'
