{
 "title": "M5 Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Backend Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{namespace=\"default\", container=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{namespace=\"default\", container=\"frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger Traces by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "sum(jaeger:traces_total) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend 40X Http Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum({namespace=\"default\", container=\"backend\", status=\"404\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({namespace=\"default\", container=\"frontend\", status=\"404\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend 50X Http Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum({namespace=\"default\", container=\"backend\", status=\"500\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({namespace=\"default\", container=\"frontend\", status=\"500\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}